export enum TypeScope {
    Classes = 'Classes',
    Interfaces = 'Interfaces',
    Enums = 'Enums',
    TypeAliases = 'TypeAliases',
    Functions = 'Functions',
    Variables = 'Variables',
    Literals = 'Literals',
    Destructuring = 'Destructuring',
    ExportAssignments = 'ExportAssignments',
    Decorators = 'Decorators',
    GetAccessors = 'GetAccessors',
    SetAccessors = 'SetAccessors',
    Methods = 'Methods',
    MethodsOfInterface = 'MethodsOfInterface',
    CallSignaturesOfInterface = 'CallSignaturesOfInterface',
    CallSignaturesOfLiteral = 'CallSignaturesOfLiteral',
    CallSignaturesOfVariable = 'CallSignaturesOfVariable',
    Constructors = 'Constructors',
    ConstructorsOfInterface = 'ConstructorsOfInterface',
}
