name: Node CI

on:
  push:
    branches: 
      - master
      - develop
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, test, and coverage
      run: |
        npm install
        npm run build --if-present
        npm test
        npm run coverage --if-present
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: coverage/lcov.info
        flags: unittests #optional
        name: codecov-umbrella #optional
